# ============================================================
# Bluetooth
# ============================================================

CONFIG_ZMK_BLE=y

# This is currently a single keyboard.
CONFIG_ZMK_SPLIT=n


# ============================================================
# Matrix
# ============================================================
   

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5


# ============================================================
# Encoder
# ============================================================

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y


# ============================================================
# OLED DISPLAY
# ============================================================

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y